Azure/azure-webjobs-sdk-extensions

src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/Samples/ApiHubSamples.cs
src/ExtensionsSample/packages.config
src/WebJobs.Extensions.ApiHub.NuGet/WebJobs.Extensions.ApiHub.nuspec
src/WebJobs.Extensions.ApiHub/ApiHubScriptBindingProvider.cs
src/WebJobs.Extensions.ApiHub/Common/GenericFileTriggerBindingProvider.cs
src/WebJobs.Extensions.ApiHub/Config/ApiHubConfiguration.cs
src/WebJobs.Extensions.ApiHub/Listener/ApiHubListener.cs
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.ApiHub/packages.config
test/WebJobs.Extensions.Tests/Extensions/ApiHub/ApiHubBindingEndToEndTests.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
test/WebJobs.Extensions.Tests/packages.config

This is needed for Antares scale controller as well.

Update to have Apihub file triggers save latest trigger status in case of down times

---

src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs

fixing duplicate timer trigger issue

---

src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/packages.config
src/Sample.Extension/Sample.Extension.csproj
src/Sample.Extension/packages.config
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.ApiHub/packages.config
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
src/WebJobs.Extensions.DocumentDB/packages.config
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.MobileApps/packages.config
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
src/WebJobs.Extensions.NotificationHubs/packages.config
src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.SendGrid/packages.config
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions.Twilio/packages.config
src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs
src/WebJobs.Extensions/WebJobs.Extensions.csproj
src/WebJobs.Extensions/packages.config
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
test/WebJobs.Extensions.Tests/packages.config

Should address https://github.com/Azure/azure-webjobs-sdk-script/issues/558.
I've also included a commit to move our nugets forward.

prevent TimerListener from firing after it's been stopped

---

src/ExtensionsSample/App.config
src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/packages.config
src/Sample.Extension/Sample.Extension.csproj
src/Sample.Extension/packages.config
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.ApiHub/packages.config
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
src/WebJobs.Extensions.DocumentDB/packages.config
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.MobileApps/packages.config
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
src/WebJobs.Extensions.NotificationHubs/packages.config
src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.SendGrid/app.config
src/WebJobs.Extensions.SendGrid/packages.config
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions.Twilio/packages.config
src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs
src/WebJobs.Extensions/WebJobs.Extensions.csproj
src/WebJobs.Extensions/packages.config
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
test/WebJobs.Extensions.Tests/app.config
test/WebJobs.Extensions.Tests/packages.config

Timer: moving schedule logging to Info

---

src/WebJobs.Extensions.ApiHub/Listener/ApiHubListener.cs

ApiHubFile triggers do not get fired if the path gets updated after inital setup

Fix for https://github.com/Azure/azure-webjobs-sdk-extensions/issues/158

---

src/WebJobs.Extensions.NotificationHubs/Bindings/NotificationHubAsyncCollector.cs
src/WebJobs.Extensions.NotificationHubs/Bindings/NotificationHubScriptBindingProvider.cs
src/WebJobs.Extensions.NotificationHubs/Config/DefaultNotificationHubServiceFactory.cs
src/WebJobs.Extensions.NotificationHubs/Config/INotificationHubClientServiceFactory.cs
src/WebJobs.Extensions.NotificationHubs/Config/NotificationHubsConfiguration.cs
src/WebJobs.Extensions.NotificationHubs/NotificationHubAttribute.cs
src/WebJobs.Extensions.NotificationHubs/Services/NotificationHubClientService.cs
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
test/WebJobs.Extensions.Tests/Extensions/NotificationHubs/NotificationHubAsyncCollectorTests.cs
test/WebJobs.Extensions.Tests/Extensions/NotificationHubs/NotificationHubConfigurationTests.cs
test/WebJobs.Extensions.Tests/Extensions/NotificationHubs/NotificationHubEndToEndTests.cs

[NotificaitonHubs] Add EnableTestSend

---

src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs

There was a bug here with how we stored the ScheduleStatus when we found clock skew and had to adjust the next invocation forward. We'd write the `Last` value as the actual time the trigger fired. However, if the host restarted, it'd take that time into consideration and think that the schedule had changed ([this code determines that](https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs#L74-L86)). That would then incorrectly report that the timer was past due.
Now we'll store the adjusted invocation time, meaning all the future calculations should work as if the trigger fired exactly on time.
These things are tough to debug, so I added a couple of extra lines of verbose logging as well. That will help in …

Timer: fixing 'PastDue' bug with clock skew

---

src/WebJobs.Extensions.SendGrid.Nuget/WebJobs.Extensions.SendGrid.nuspec
tools/NuGetProj.targets

updating SendGrid nuspec to restrict future updates past v8

---

CustomDictionary.xml
src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/Models/CustomQueueInput.cs
src/ExtensionsSample/Models/ItemDoc.cs
src/ExtensionsSample/Samples/DocumentDBSamples.cs
src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBEnumerableBuilder.cs
src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBJArrayBuilder.cs
src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs
src/WebJobs.Extensions.DocumentDB/DocumentDBAttribute.cs
src/WebJobs.Extensions.DocumentDB/DocumentDBSqlResolutionPolicy.cs
src/WebJobs.Extensions.DocumentDB/Services/DocumentDBService.cs
src/WebJobs.Extensions.DocumentDB/Services/DocumentQueryResponse.cs
src/WebJobs.Extensions.DocumentDB/Services/IDocumentDBService.cs
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBConfigurationTests.cs
test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBEndToEndTests.cs
test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBEnumerableBuilderTests.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj

Addresses https://github.com/Azure/azure-webjobs-sdk-script/issues/289

documentdb query binding support

---

src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/packages.config
src/Sample.Extension/Sample.Extension.csproj
src/Sample.Extension/packages.config
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.ApiHub/packages.config
src/WebJobs.Extensions.DocumentDB/DocumentDBAttribute.cs
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
src/WebJobs.Extensions.DocumentDB/packages.config
src/WebJobs.Extensions.MobileApps/MobileTableAttribute.cs
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.MobileApps/packages.config
src/WebJobs.Extensions.NotificationHubs/NotificationHubAttribute.cs
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
src/WebJobs.Extensions.NotificationHubs/packages.config
src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec
src/WebJobs.Extensions.SendGrid/SendGridAttribute.cs
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.SendGrid/packages.config
src/WebJobs.Extensions.Twilio/TwilioSMSAttribute.cs
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions.Twilio/packages.config
src/WebJobs.Extensions/WebJobs.Extensions.csproj
src/WebJobs.Extensions/packages.config
test/WebJobs.Extensions.Tests/Common/TestNameResolver.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
test/WebJobs.Extensions.Tests/packages.config

Nuget update + AppSetting

---

src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/packages.config
src/Packages/Packages.csproj
src/Sample.Extension/Sample.Extension.csproj
src/Sample.Extension/packages.config
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.ApiHub/packages.config
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
src/WebJobs.Extensions.DocumentDB/packages.config
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.MobileApps/packages.config
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
src/WebJobs.Extensions.NotificationHubs/packages.config
src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.SendGrid/packages.config
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions.Twilio/packages.config
src/WebJobs.Extensions/WebJobs.Extensions.csproj
src/WebJobs.Extensions/packages.config
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
test/WebJobs.Extensions.Tests/packages.config

Update to SDK Nuget 10646

---

test/WebJobs.Extensions.Tests/Extensions/Http/HttpTriggerEndToEndTests.cs
test/WebJobs.Extensions.Tests/Extensions/SendGrid/SendGridEndToEndTests.cs

PR #228 showed that we're missing a couple of traits so community test runs in AppVeyor don't complete successfully.

adding missing E2E test traits

---

src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/packages.config
src/Sample.Extension/Sample.Extension.csproj
src/Sample.Extension/packages.config
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.ApiHub/packages.config
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
src/WebJobs.Extensions.DocumentDB/packages.config
src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj
src/WebJobs.Extensions.Http/packages.config
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.MobileApps/packages.config
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
src/WebJobs.Extensions.NotificationHubs/packages.config
src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.SendGrid/packages.config
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions.Twilio/packages.config
src/WebJobs.Extensions/WebJobs.Extensions.csproj
src/WebJobs.Extensions/packages.config
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
test/WebJobs.Extensions.Tests/packages.config

This SDK was built from the v2.x branch to test that engineering infrastructure.
No functional changes.

Update extensions to latest SDK, 10851

---

src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs
src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs
src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerConstants.cs
test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs

Fixing CosmosDBTrigger binding (#269)

---

WebJobs.Extensions.sln
src/ExtensionsSample/ErrorNotifier.cs
src/ExtensionsSample/ExtensionsSample.csproj
src/ExtensionsSample/Program.cs
src/ExtensionsSample/Samples/ErrorMonitoringSamples.cs
src/ExtensionsSample/Samples/SendGridSamples.cs
src/Sample.Extension/SampleJobHostConfigurationExtensions.cs
src/WebJobs.Extensions.SendGrid/Bindings/SendGridHelpers.cs
src/WebJobs.Extensions.SendGrid/Bindings/SendGridMessageAsyncCollector.cs
src/WebJobs.Extensions.SendGrid/Client/ISendGridClient.cs
src/WebJobs.Extensions.SendGrid/Client/SendGridClient.cs
src/WebJobs.Extensions.SendGrid/Config/ISendGridClientFactory.cs
src/WebJobs.Extensions.SendGrid/Config/SendGridClientFactory.cs
src/WebJobs.Extensions.SendGrid/Config/SendGridConfiguration.cs
src/WebJobs.Extensions.SendGrid/Config/SendGridJobHostConfigurationExtensions.cs
src/WebJobs.Extensions.SendGrid/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.SendGrid/SendGridAttribute.cs
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
test/WebJobs.Extensions.Tests/Extensions/SendGrid/SendGridEndToEndTests.cs
test/WebJobs.Extensions.Tests/Extensions/SendGrid/SendGridHelpersTests.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj

Addresses https://github.com/Azure/azure-webjobs-sdk-extensions/issues/243

Migrating SendGrid extension to .NET core (#243)

---

src/WebJobs.Extensions/Extensions/Timers/Scheduling/CronSchedule.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/CronScheduleTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/ScheduleMonitorTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/TimerInfoTests.cs

This is related to this issue #309.
I've also altered the tests so they don't have to run in an en-us culture.

Support 5 part cron expressions

---

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttribute.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerBinding.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs

Cherry-picking v2.x PRs to dev

---

build/common.props

Linking source/mapping source path to GitHub

---

src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/TimerScheduleTests.cs

Updated message to show if environment variable has been resolved for the cron schedule
Resolves #346

Update error message for cron schedule

---

src/WebJobs.Extensions.CosmosDB/Config/CosmosDBConfiguration.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/Trigger/CosmosDBTriggerAttributeTests.cs

Cherry-pick of #370.
Fixes #322 in `dev`.

[CosmosDBTrigger] fixing issue with NameResolver

---

WebJobs.Extensions.proj
appveyor.yml
src/Common/CommonAssemblyInfo.cs
src/WebJobs.Extensions.ApiHub/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj
src/WebJobs.Extensions.DocumentDB/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj
src/WebJobs.Extensions.Http/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj
src/WebJobs.Extensions.MobileApps/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.NotificationHubs/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj
src/WebJobs.Extensions.SendGrid/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.Twilio/Properties/AssemblyInfo.cs
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions/Properties/AssemblyInfo.cs
src/WebJobs.Extensions/WebJobs.Extensions.csproj
tools/NuGetProj.settings.targets

Similar changes to the SDK repo here: https://github.com/Azure/azure-webjobs-sdk/pull/1599

improving build process

---

appveyor.yml

we don't really use the tag name

reformat appveyor.yml

---

src/WebJobs.Extensions.Http/Config/HttpExtensionConfiguration.cs
src/WebJobs.Extensions.Http/Extensions/HttpRequestExtensions.cs
src/WebJobs.Extensions.Http/HttpDirectRequestBindingProvider.cs
src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs
test/WebJobs.Extensions.Tests/Extensions/Http/HttpTriggerBindingTests.cs

Required fixes to the http extension to allow us to reenable some Functions tests

Http binding extension fixes

---

src/ExtensionsSample/ExtensionsSample.csproj
src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj

This PR updates CFP library to 1.3.3, which includes stability improvements and compatibility with the emulator.
Fixes https://github.com/Azure/azure-functions-host/issues/2766.
Fixes https://github.com/Azure/azure-functions-host/issues/2259

Update Cosmos DB Change Feed Processor to 1.3.3

---

src/WebJobs.Extensions.CosmosDB/Config/CosmosDBConfiguration.cs
src/WebJobs.Extensions.CosmosDB/Config/DefaultCosmosDBServiceFactory.cs
src/WebJobs.Extensions.CosmosDB/Config/ICosmosDBServiceFactory.cs
src/WebJobs.Extensions.CosmosDB/Services/CosmosDBService.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/CosmosDBEnumerableBuilderTests.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/CosmosDBMockEndToEndTests.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/TestCosmosDBServiceFactory.cs
test/WebJobs.Extensions.Tests/Extensions/CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs

This PR is related to https://github.com/Azure/azure-webjobs-sdk-extensions/pull/400 and https://github.com/Azure/azure-webjobs-sdk-extensions/pull/417 and it's meant to port the changes to the dev branch.

Porting CosmosDB ConnectionMode PR to dev branch

---

src/WebJobs.Extensions.CosmosDB/Config/CosmosDBConfiguration.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerBinding.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs
test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs

This is a port of https://github.com/Azure/azure-webjobs-sdk-extensions/pull/433 to the `dev` branch.

[Cosmos DB] [V2] Adding tracing and retry fix for Trigger

---

src/WebJobs.Extensions.SendGrid/Bindings/SendGridMessageAsyncCollector.cs
src/WebJobs.Extensions.Twilio/Bindings/TwilioSmsMessageAsyncCollector.cs

Resolves #416.
There was no existing unit test coverage for the flush path, didn't feel like it was worth introducing new interfaces for the purposes of unit testing this small change.
As an added bonus, the implementation is now thread-safe.

Fix #416 - sendgrid and twilio async collectors dont clear buffer on flush

---

src/WebJobs.Extensions/Extensions/Files/Bindings/FileTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions/Extensions/Files/Bindings/FileTriggerBinding.cs
src/WebJobs.Extensions/Extensions/Files/Config/FilesExtensionConfigProvider.cs
src/WebJobs.Extensions/Extensions/Files/Config/FilesOptions.cs
src/WebJobs.Extensions/Extensions/Files/Config/FilesWebJobsBuilderExtensions.cs
src/WebJobs.Extensions/Extensions/Files/Listener/DefaultFileProcessorFactory.cs
src/WebJobs.Extensions/Extensions/Files/Listener/FileListener.cs
src/WebJobs.Extensions/Extensions/Files/Listener/FileProcessor.cs
src/WebJobs.Extensions/Extensions/Files/Listener/FileProcessorFactoryContext.cs
src/WebJobs.Extensions/Extensions/Files/Listener/IFileProcessorFactory.cs
src/WebJobs.Extensions/Extensions/Timers/Bindings/TimerTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions/Extensions/Timers/Bindings/TimerTriggerBinding.cs
src/WebJobs.Extensions/Extensions/Timers/Config/TimerWebJobsBuilderExtensions.cs
src/WebJobs.Extensions/Extensions/Timers/Config/TimersExtensionConfigProvider.cs
src/WebJobs.Extensions/Extensions/Timers/Config/TimersOptions.cs
src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/StorageScheduleMonitor.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Bindings/TimerTriggerBindingTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/StorageScheduleMonitorTests.cs

Applying similar changes to those in core SDK for https://github.com/Azure/azure-webjobs-sdk/issues/1833.

Move Options services to DI (#1833)

---

src/ExtensionsSample/ExtensionsSample.csproj
src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj
src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions/Extensions/Timers/Scheduling/StorageScheduleMonitor.cs
src/WebJobs.Extensions/WebJobs.Extensions.csproj
test/WebJobs.Extensions.CosmosDB.Tests/WebJobs.Extensions.CosmosDB.Tests.csproj
test/WebJobs.Extensions.Http.Tests/Helpers/JobHostTestHelpers.cs
test/WebJobs.Extensions.Http.Tests/WebJobs.Extensions.Http.Tests.csproj
test/WebJobs.Extensions.MobileApps.Tests/WebJobs.Extensions.MobileApps.Tests.csproj
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/StorageScheduleMonitorTests.cs

To take connection string changes

Pulling in latest SDK

---

build/common.props

Addresses https://github.com/Azure/Azure-Functions/issues/909

Add nuget package tags to common properties file

---

src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttribute.cs
src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs
src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerListener.cs
test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs

This PR ports the changes in V3 to V2 from this PR https://github.com/Azure/azure-webjobs-sdk-extensions/pull/467

[CosmosDB] Start/Stop and StartFromBeginning on V2

---

src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerListener.cs
test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBListenerTests.cs
test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj

This PR ports the https://github.com/Azure/azure-webjobs-sdk-extensions/pull/473 PR to V2 branch.

[Cosmos DB] Fixing retry scenario port to V2

---

run-tests.ps1
src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/ConstantSchedule.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/CronSchedule.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/DailySchedule.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/WeeklySchedule.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/TimerScheduleTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/TimerTriggerEndToEndTests.cs

[Timer] conditionally adjust for DST

---

build/common.props

Fixing package EULA link

---

src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj
src/WebJobs.Extensions/WebJobs.Extensions.csproj

Updating Extensions and CosmosDB versions as they have changed since last release. Since we no longer need to release each extension with every revision, I'm starting to separate out their versioning.

updating versions

---

src/WebJobs.Extensions.Http/Routing/WebJobsRouter.cs

https://github.com/Azure/azure-functions-host/issues/2590

Catch all routes in proxies should not override /admin routes.

---

src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj

Only Http.Extensions have changed since last version update

Updating WebJobs.Extensions.Http to 3.0.2

---

build/common.props
src/WebJobs.Extensions.Http/Config/HttpOptions.cs

This reverts commit e6d139e8f6e0f1a77b4c45e9b8809cd3f5eecb67.

Revert "Adding https options to remove .NET headers"

---

build/common.props

Update Extensions version for new release

---

src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs

Missed this occurrence when I did #585.

changing EnableRewind to EnableBuffering

---

src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions/Framework/Bindings/StreamValueBinder.cs

This is causing issues due to AllowSynchronousIO now being false by default in ASP.NET Core 3.

changing synchronous stream.Write() call to async

---

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerBinding.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs
src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerMetrics.cs
src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj
src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions/WebJobs.Extensions.csproj
test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBListenerTests.cs

Adding CosmosDB support for runtime scaling with unit tests.

---

build/common.props
src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj

Updating cosmos DB packages

---

build/common.props
src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs

removing check for application/json before calling EnableBuffering()

---

README.md

Same as https://github.com/Azure/azure-webjobs-sdk-extensions/pull/665 but for dev

Update code snippet in readme to use hostbuilder

---

README.md

The error trigger section had a broken link that was reported, and anyone landing on it from functions land is going to be confused anyway. Also since Mobile Apps is pretty much gone I removed that section too.

Remove Error Trigger and Mobile Apps from readme

---

build/common.props
src/WebJobs.Extensions.Http/Routing/IWebJobsRouter.cs
src/WebJobs.Extensions.Http/Routing/WebJobsRouter.cs
test/WebJobs.Extensions.Http.Tests/WebJobsRouterTests.cs

As per other discussion reverting changes to the interface.

Revert changes to IWebJobsRouter

---

src/WebJobs.Extensions/Extensions/Timers/Bindings/TimerTriggerAttributeBindingProvider.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/CronSchedule.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleMonitor.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/ScheduleStatus.cs
src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs
src/WebJobs.Extensions/WebJobs.Extensions.csproj
test/WebJobs.Extensions.Tests/Extensions/Timers/Bindings/TimerTriggerBindingTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs
test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/TimerScheduleTests.cs

Fix for https://github.com/Azure/azure-webjobs-sdk-extensions/issues/674. Will also make this fix to v2.x.

Fix for schedule monitor enablement (#674)

---

build/common.props
src/WebJobs.Extensions.Http/Routing/WebJobsRouter.cs

addresses: https://github.com/Azure/azure-functions-host/pull/6993

Disable admin overrides except admin/warmup in WebJobsRouter.

---

build/common.props
src/ExtensionsSample/ExtensionsSample.csproj
src/WebJobs.Extensions.CosmosDB/CosmosDBAttribute.cs
src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj
src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj
src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj
src/WebJobs.Extensions.SendGrid/SendGridAttribute.cs
src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
src/WebJobs.Extensions.Twilio/Config/TwilioWebJobsBuilderExtensions.cs
src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj
src/WebJobs.Extensions/WebJobs.Extensions.csproj

[pack] Enabling XML docs for all extensions

---

build/common.props
src/WebJobs.Extensions.Http/Routing/WebJobsRouter.cs

This PR will take care of this: https://github.com/Azure/azure-functions-host/pull/6993

Revert check for admin endpoints in Webjobs.Extensions

---

src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs
test/WebJobs.Extensions.Http.Tests/HttpTriggerBindingTests.cs

E2E test in host:
https://github.com/Azure/azure-functions-host/pull/7053

[pack] Deserialization of chunked requests does not work (Issue #702)
