Azure/azure-webjobs-sdk-extensions

README.md
UseFiles() method lacked parenthesis and semicolon.
=> Fix typo in readme sample code

src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBAsyncCollector.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBAttributeBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBItemValueBinder.cs, src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs, src/WebJobs.Extensions.DocumentDB/DocumentDBContext.cs, src/WebJobs.Extensions.DocumentDB/DocumentDBUtility.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBAsyncCollectorTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBAttributeBindingProviderTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBContextTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBTestUtility.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBUtilityTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
I accidentally removed the Task.Delay in my last checkin. That effectively broke docdb under any kind of stress where clients were throttled.
=> fixing docdb retry bug

src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/Models/ItemDoc.cs, src/ExtensionsSample/Samples/DocumentDBSamples.cs, src/ExtensionsSample/packages.config, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBAttributeBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBItemBinding.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBItemBindingContext.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBItemValueBinder.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBOutputBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/DocumentDBAttribute.cs, src/WebJobs.Extensions.DocumentDB/DocumentDBContext.cs, src/WebJobs.Extensions.DocumentDB/Services/DocumentDBService.cs, src/WebJobs.Extensions.DocumentDB/Services/IDocumentDBService.cs, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/packages.config, src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj, src/WebJobs.Extensions.NotificationHubs/packages.config, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBAttributeBindingProviderTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBItemBindingTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBItemValueBinderTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBOutputBindingProviderTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/packages.config
Adds support for `PartitionKey` and `CollectionThroughput` on `DocumentDbAttribute`. Also changes `CreateIfNotExists` to only apply to output bindings. For background, see: https://azure.microsoft.com/en-us/documentation/articles/documentdb-partition-data/
The behavior of the two new properties is as such:
- `PartitionKey` on an **output** paramter: If  `CreateIfNotExists` is `true`, the collection will be created with this partition key path. If the value is invalid, DocumentClient will throw an exception.
- `PartitionKey` on an **input** parameter: The value will be used in conjunction with `Id` to lookup the record. If there is no partition for the collection, this value is not required.
- `CollectionThroughput` on an **output** parameter: If `CreateIfNotExists` is `true` and the value …
=> docdb partition support

src/WebJobs.Extensions.ApiHub/ApiHubFileAttribute.cs, src/WebJobs.Extensions.ApiHub/Config/ApiHubConfiguration.cs, src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs, src/WebJobs.Extensions.DocumentDB/DocumentDBAttribute.cs, src/WebJobs.Extensions.MobileApps/Config/MobileAppsConfiguration.cs, src/WebJobs.Extensions.MobileApps/MobileTableAttribute.cs, src/WebJobs.Extensions.NotificationHubs/Config/NotificationHubsConfiguration.cs, src/WebJobs.Extensions.NotificationHubs/NotificationHubAttribute.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBConfigurationTests.cs, test/WebJobs.Extensions.Tests/Extensions/MobileApps/MobileAppsConfigurationTests.cs
Addresses #67.
@safihamid @emilcicos FYI -- I've renamed one of the ApiHubAttribute properties (Key -> ConnectionStringSetting) to match the convention that I'm introducing here. I'm not 100% sure that's the right name. I'll wait for your 'OK' before merging.
=> Renaming all key lookup attribute properties to end with 'Setting'

src/WebJobs.Extensions.MobileApps/Config/MobileAppsConfiguration.cs, src/WebJobs.Extensions.MobileApps/MobileTableAttribute.cs, test/WebJobs.Extensions.Tests/Extensions/MobileApps/MobileAppsConfigurationTests.cs, test/WebJobs.Extensions.Tests/Extensions/MobileApps/MobileTableEndToEndTests.cs
The issue here was that ApiKey has special behavior so you can override the default value if you need to. That behavior is defined here: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/master/src/WebJobs.Extensions.MobileApps/MobileTableAttribute.cs#L53-L56.
When I changed this to use AutoResolve, I didn't add any E2E tests that actually went through the AttributeCloner. I forgot that the AttributeCloner will throw if it doesn't find any matching lookup, and it treats an empty string as a valid key (maybe it shouldn't - but we can address that elsewhere). So if you tried to use ApiKey="", it would throw because the AttributeCloner could not find any value in the INameResolver that matched "".
The fix here is to not use AutoResolve and perform this resolution myself. I also …
=> MobileTable: fixing a bug with ApiKey behavior

src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/Samples/ApiHubTableSamples.cs, src/ExtensionsSample/packages.config, src/WebJobs.Extensions.ApiHub.NuGet/WebJobs.Extensions.ApiHub.nuspec, src/WebJobs.Extensions.ApiHub/Table/ApiHubTableAttributeExtensions.cs, src/WebJobs.Extensions.ApiHub/Table/ConnectionFactory.cs, src/WebJobs.Extensions.ApiHub/Table/TableAsyncCollector.cs, src/WebJobs.Extensions.ApiHub/Table/TableBinding.cs, src/WebJobs.Extensions.ApiHub/Table/TableClientBinding.cs, src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj, src/WebJobs.Extensions.ApiHub/packages.config, test/WebJobs.Extensions.Tests/Extensions/ApiHub/ApiHubTableBindingTests.cs, test/WebJobs.Extensions.Tests/Extensions/ApiHub/FakeConnection.cs, test/WebJobs.Extensions.Tests/Extensions/ApiHub/FakeConnectionFactory.cs, test/WebJobs.Extensions.Tests/Extensions/ApiHub/FakeTabularConnectorAdapter.cs, test/WebJobs.Extensions.Tests/Extensions/NotificationHubs/NotificationHubConfigurationTests.cs, test/WebJobs.Extensions.Tests/Extensions/NotificationHubs/NotificationHubEndToEndTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/packages.config
Update to latest version of ApiHub SDK to add support for FTP/SFTP triggers as well as unify ApiHub Table public namespaces.
=> Update to latest version of ApiHub SDK to add support for FTP/SFTP 

src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBScriptBindingProvider.cs
Updating the DocumentDB extension to export the SDK assembly so users are no longer forced to add a Nuget reference.
=> Exporting DocumentDB assembly

src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBAsyncCollector.cs, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBItemValueBinder.cs, src/WebJobs.Extensions.DocumentDB/DocumentDBUtility.cs, src/WebJobs.Extensions.DocumentDB/Services/DocumentDBService.cs, src/WebJobs.Extensions.DocumentDB/Services/IDocumentDBService.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBEndToEndTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBItemValueBinderTests.cs
=> DocDB: supporting strings as input and output parameters

src/WebJobs.Extensions/Extensions/Timers/Scheduling/DailySchedule.cs, src/WebJobs.Extensions/Extensions/Timers/Scheduling/TimerSchedule.cs, src/WebJobs.Extensions/Extensions/Timers/Scheduling/WeeklySchedule.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/CronScheduleTests.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/DailyScheduleTests.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/WeeklyScheduleTests.cs
GetNextOccurrence should not return same occurrence when now is equal to an occurrence. This fix is inspired by the issue reported in https://github.com/Azure/azure-webjobs-sdk-extensions/pull/164.
=> GetNextOccurrence Scheduling fix

src/WebJobs.Extensions/Extensions/Core/Bindings/ErrorTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions/Extensions/Core/Listener/ErrorTriggerListener.cs, src/WebJobs.Extensions/Extensions/Core/Monitoring/SlidingWindowTraceFilter.cs, src/WebJobs.Extensions/Extensions/Core/Monitoring/TraceFilter.cs, test/WebJobs.Extensions.Tests/Extensions/Core/ErrorTriggerEndToEndTests.cs, test/WebJobs.Extensions.Tests/Extensions/Core/ErrorTriggerListenerTests.cs, test/WebJobs.Extensions.Tests/Extensions/Core/SlidingWindowTraceFilterTests.cs, test/WebJobs.Extensions.Tests/Extensions/Core/TraceFilterTests.cs, test/WebJobs.Extensions.Tests/Extensions/Core/TraceMonitorTests.cs
Updating TraceFilter to return a snapshot of TraceEvents instead of live collection
Fix for https://github.com/Azure/azure-webjobs-sdk-extensions/issues/176
=> Updating TraceFilter to return a snapshot of TraceEvents instead of live collection

src/WebJobs.Extensions/Extensions/CoreExtensionsScriptBindingProvider.cs, src/WebJobs.Extensions/Utility.cs, src/WebJobs.Extensions/WebJobs.Extensions.csproj, test/WebJobs.Extensions.Tests/Extensions/Core/CoreExtensionsScriptBindingProvider.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
Fixes https://github.com/Azure/azure-webjobs-sdk-extensions/issues/181. We now only do these schedule restrictions in Dynamic plan.
=> Fix TimerTrigger Dynamic schedule restrictions (#181)

src/ExtensionsSample/Samples/DocumentDBSamples.cs, src/WebJobs.Extensions.DocumentDB.Nuget/WebJobs.Extensions.DocumentDB.nuspec, src/WebJobs.Extensions.DocumentDB/Bindings/DocumentDBItemValueBinder.cs, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/packages.config, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBEndToEndTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBItemValueBinderTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/packages.config
Addresses #198 
The issue was that we were storing all of the 'hidden' values in the original document in `_originalValue`. Since those weren't passed to the function, we'd see them and think that the object had changed. Now we do the conversion to the destination object before storing the `_originalValue`. Then, we can correctly compare whether any changes were made.
Example:
Document comes back as `{"id":"abc", "_ts":100}`, but if your POCO only has an Id, you won't get the `_ts` property, yet we'd store it in `_originalValue`. When we'd check to see if it had changed, we'd see the missing `_ts` and think you had changed it, prompting an update.
=> DocDB: fixing bug in change detection for updates

src/WebJobs.Extensions.Http/HttpTriggerAttribute.cs
Right now through HttpTrigger forces you to add authtype if you want to restrict httpTrigger to a certain http methods. However the if the HttpTrigger is of type webhook Authlevel does not apply. Adding another constructor to specify only methods parameter.
=> Adding a constructor to the HttpTriggerAttribute to specify only methods

src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/packages.config, src/Sample.Extension/Sample.Extension.csproj, src/Sample.Extension/packages.config, src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj, src/WebJobs.Extensions.ApiHub/packages.config, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/packages.config, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.Http/packages.config, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.MobileApps/packages.config, src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj, src/WebJobs.Extensions.NotificationHubs/packages.config, src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec, src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj, src/WebJobs.Extensions.SendGrid/packages.config, src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj, src/WebJobs.Extensions.Twilio/packages.config, src/WebJobs.Extensions/WebJobs.Extensions.csproj, src/WebJobs.Extensions/packages.config, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/packages.config
Next stage of https://github.com/Azure/azure-webjobs-sdk/issues/1129 -- no more direct App Insights dependencies here.
=> updating to latest webjobs nugets

src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.Http/Utility.cs, test/WebJobs.Extensions.Tests/Extensions/Http/HttpTriggerBindingTests.cs
Required to support new path based binding expressions for non strongly typed languages in Functions (e.g. Node.js)
=> Allowing objects to flow through binding data

src/WebJobs.Extensions.DocumentDB/DocumentDBSqlResolutionPolicy.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBSqlResolutionPolicyTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
The DocDB binding currently does not handle duplicate parameters in `SqlQuery`. For instance:
SELECT * FROM c WHERE c.id = {foo} AND c.value = {foo}
This results in an exception: `mscorlib: An item with the same key has already been added.`
- Changed behavior such that only a single `SqlParameter` is created for duplicate parameter names
- Fixed "same key" exception
- Added tests
=> Fix docdb issue with duplicate SQL query parameters

src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/packages.config, src/Sample.Extension/Sample.Extension.csproj, src/Sample.Extension/packages.config, src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj, src/WebJobs.Extensions.ApiHub/packages.config, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/packages.config, src/WebJobs.Extensions.Http/Config/HttpExtensionConfiguration.cs, src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.Http/packages.config, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.MobileApps/packages.config, src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj, src/WebJobs.Extensions.NotificationHubs/packages.config, src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec, src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj, src/WebJobs.Extensions.SendGrid/packages.config, src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj, src/WebJobs.Extensions.Twilio/packages.config, src/WebJobs.Extensions/WebJobs.Extensions.csproj, src/WebJobs.Extensions/packages.config, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/packages.config
Requires a latest SDK build.
Specifically minimize the code deltas here to support the parallel migration to core.
=> Update Http to support SDK return values

CustomDictionary.xml, WebJobs.Extensions.sln, src/ExtensionsSample/App.config, src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/Samples/CosmosDBTriggerSamples.cs, src/ExtensionsSample/packages.config, src/WebJobs.Extensions.DocumentDB.Nuget/WebJobs.Extensions.DocumentDB.nuspec, src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerConstants.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerListener.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerObserver.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerParameterDescriptor.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerValueBinder.cs, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/app.config, src/WebJobs.Extensions.DocumentDB/packages.config, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeTests.cs, test/WebJobs.Extensions.Tests/PublicSurfaceTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/app.config, test/WebJobs.Extensions.Tests/packages.config
This change adds the `[CosmosDBTrigger]` extension that allows users to subscribe to collection changes.
When changes are detected, the trigger will fire and provide the user with a `IReadOnlyList<Document>` to read and use the documents. The Trigger can also be chained with the `DocumentDB` output binding as demonstrated in one of the samples.
Due to this ability to chain Trigger and Binding, the Trigger has a separate explicit set of Connection Strings to avoid infinite loops. Support for AppSettings, Configuration and Attribute set of the Connection Strings has also been added.
Internally it uses the [ChangeFeedProcessor](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/ChangeFeedProcessor) distributed as a Nuget package. Package is still in publishing process. …
=> CosmosDB Change Feed trigger

src/WebJobs.Extensions/Extensions/Core/Bindings/ExecutionContextBindingProvider.cs, src/WebJobs.Extensions/Extensions/Core/Config/CoreJobHostConfigurationExtensions.cs, src/WebJobs.Extensions/Extensions/Core/ExecutionContext.cs, test/WebJobs.Extensions.Tests/Extensions/Core/CoreBindingEndToEndTests.cs
Add FunctionAppDirectory path, set to  something determined by the host. Script runtime will set this to ScriptConfig.RootScriptPath
Also fix ExecutionContext.FunctionName to properly honor [FunctionName] attribute.
=> Fixups to ExecutionContext

src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerConstants.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
CosmosDBTrigger was not correctly reading ConnectionStringSetting from AppSettings and was treating it as a normal string.
=> Fixing CosmosDBTrigger ConnectionStringSetting binding

WebJobs.Extensions.sln, src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/Program.cs, src/ExtensionsSample/Samples/TwilioSamples.cs, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.Twilio/Bindings/TwilioSmsMessageAsyncCollector.cs, src/WebJobs.Extensions.Twilio/Config/TwilioJobHostConfigurationExtensions.cs, src/WebJobs.Extensions.Twilio/Config/TwilioSmsConfiguration.cs, src/WebJobs.Extensions.Twilio/Properties/AssemblyInfo.cs, src/WebJobs.Extensions.Twilio/TwilioSMSAttribute.cs, src/WebJobs.Extensions.Twilio/TwilioSmsContext.cs, src/WebJobs.Extensions.Twilio/Utility.cs, src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj, src/WebJobs.Extensions/WebJobs.Extensions.csproj, test/WebJobs.Extensions.Tests/Extensions/Twilio/TwilioSmsConfigurationTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj
Addresses https://github.com/Azure/azure-webjobs-sdk-extensions/issues/242.
There were a bunch of changes required to the object model of the extension, because Twilio changed their object model quite a bit. See https://www.twilio.com/docs/libraries/csharp/migrating-your-csharp-dot-net-application-twilio-sdk-4x-5x.
=> Migrating Twilio to .NET Core

CustomDictionary.xml, src/WebJobs.Extensions.ApiHub/WebJobs.Extensions.ApiHub.csproj, src/WebJobs.Extensions.ApiHub/packages.config, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/packages.config, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.Http/packages.config, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.MobileApps/packages.config, src/WebJobs.Extensions.NotificationHubs/WebJobs.Extensions.NotificationHubs.csproj, src/WebJobs.Extensions.NotificationHubs/packages.config, src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj, src/WebJobs.Extensions.SendGrid/packages.config, src/WebJobs.Extensions/WebJobs.Extensions.csproj, src/WebJobs.Extensions/packages.config, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
This change enables executing the Trigger with a test payload from the Functions UI.
=> Adding support for JSON string values in Cosmos DB Trigger binding

src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
Fixes #316 
This change will try to pull the values of the `DatabaseName`, `CollectionName`, `LeaseDatabaseName` and `LeaseCollectionName` using the NameResolver first before using the input values.
=> Resolving Cosmos DB Trigger attribute values with NameResolver

src/WebJobs.Extensions.Http/HttpTriggerAttribute.cs, src/WebJobs.Extensions/WebJobs.Extensions.csproj
Upgrades HttpTrigger to use proposed new HandlesReturnValue attribute in azure-webjobs-sdk.
Reliant on [PR 1424](https://github.com/Azure/azure-webjobs-sdk/pull/1424) in azure-webjobs-sdk.
=> [WIP] Add new HandleReturnValue attribute to HttpTrigger.

src/WebJobs.Extensions.DocumentDB/DocumentDBUtility.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/DocumentDBTestUtility.cs
This change sends 400 RU as the default Throughput when creating a Cosmos DB collection instead of not sending anything.
The reason for this is that the default can vary between Subscription Types at this point and people were expecting 400 RU collections (the minimum) and saw 1000 RU collections being created.
=> Sending 400 RUs as default

src/WebJobs.Extensions.DocumentDB.Nuget/WebJobs.Extensions.DocumentDB.nuspec, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerListener.cs, src/WebJobs.Extensions.DocumentDB/WebJobs.Extensions.DocumentDB.csproj, src/WebJobs.Extensions.DocumentDB/packages.config, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs, test/WebJobs.Extensions.Tests/WebJobs.Extensions.Tests.csproj, test/WebJobs.Extensions.Tests/packages.config
This change exposes a number of Change Feed Host options to the `CosmosDBTrigger`:
- Lease Preffix: This is used when the user wants to share the Lease collection among several Triggers and reduces operational costs.
- Polling intervals: Exposing different interval options that allow the user to customize the frequency on which the Trigger will check for changes and other time-related features.
Additionally, `UserAgentSuffix` was added to the `DocumentClient` initializations in the trigger to identify traffic coming from the Trigger in the account's analytics.
=> Exposing Change Feed options on Trigger

appveyor.yml
evaluate boolean instead of string when `APPVEYOR_REPO_TAG == "false"`
=> fix appveyor command

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs, test/WebJobs.Extensions.Tests/Extensions/CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
This PR fills the gap between V1 and V2 by adding `LeaseCollectionPrefix` and other options to the `CosmosDBTrigger`.
Fixes https://github.com/Azure/azure-webjobs-sdk-extensions/issues/423
=> [CosmosDB] Porting leaseprefix and other options

src/WebJobs.Extensions.DocumentDB/Config/DocumentDBConfiguration.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.DocumentDB/Trigger/CosmosDBTriggerListener.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs, test/WebJobs.Extensions.Tests/Extensions/DocumentDB/Trigger/CosmosDBTriggerAttributeTests.cs
This change adds tracing inside the CosmosDBTrigger and handles the case where StopAsync might be called before Start.
It also fixes the null-ref that comes from the automatic retry when a a Function fails to load.
This PR fixes #379
This PR fixes #432
=> [Cosmos DB] Adding tracing and retry fix for Trigger

src/WebJobs.Extensions.Http/HttpExtensionConstants.cs, src/WebJobs.Extensions.Http/Routing/IWebJobsRouter.cs, src/WebJobs.Extensions.Http/Routing/WebJobsRouteBuilder.cs, src/WebJobs.Extensions.Http/Routing/WebJobsRouter.cs, test/WebJobs.Extensions.Http.Tests/WebJobsRouterTests.cs
Same changes made in #443 , but targeting a patch branch without DI changes so we can consume this in the current version of the script host.
=> Exposing router API to retrieve function route template

src/WebJobs.Extensions/Extensions/Timers/TimerTriggerAttribute.cs
Resolves https://github.com/Azure/azure-webjobs-sdk-extensions/issues/445
The existing link was confusing because it shows the format as using years instead of seconds. The updated link shows the right format.
=> Fix #445 - Update link for cron expression.

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBListenerTests.cs
Doing some unrelated testing and realized that we weren't re-setting the value here to `NotRegistered` if there was an exception. That meant the retry never succeeded. Also added a test and improved the status error to be more precise.
=> [CosmosDb] fixing trigger retry behavior

src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, test/WebJobs.Extensions.CosmosDB.Tests/WebJobs.Extensions.CosmosDB.Tests.csproj
This PR updates to the latest Change Feed Library version and increases the Cosmos DB SQL dependency tree to the latest (Core 1.9.1) as a side effect.
=> [Cosmos DB] Updating Change Feed Library to 2.0.6

src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBTestUtility.cs
This PR addresses https://github.com/Azure/azure-functions-host/issues/3419 by updating the CFP library to the latest version, and updating the Cosmos DB SDK dependency to 2.0.0.
=> [Cosmos DB] Updating CFP to 2.1.0

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
Fixes https://github.com/Azure/azure-functions-host/issues/3484
We had some test gaps where we didn't validate the correct `LeaseConnectionStringSetting` -> `ConnectionStringSetting` -> `ConnectionStrings:CosmosDB` fallback. 
I've beefed up those tests, which failed before the fix.
=> [CosmosDB] fixing connection setting fallback for leases

src/WebJobs.Extensions.CosmosDB/Bindings/CosmosDBClientBuilder.cs, src/WebJobs.Extensions.CosmosDB/Config/CosmosDBExtensionConfigProvider.cs, src/WebJobs.Extensions.CosmosDB/Config/DefaultCosmosDBServiceFactory.cs, src/WebJobs.Extensions.CosmosDB/Config/ICosmosDBServiceFactory.cs, src/WebJobs.Extensions.CosmosDB/CosmosDBAttribute.cs, src/WebJobs.Extensions.CosmosDB/CosmosDBUtility.cs, src/WebJobs.Extensions.CosmosDB/Services/CosmosDBService.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBEnumerableBuilderTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBMockEndToEndTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBUtilityTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/TestCosmosDBServiceFactory.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
This PR aims at allowing users to interact with [Multi Master accounts](https://aka.ms/multimasterdocs) by exposing the `UseMultipleWriteLocations` flag.
To be able to use Multi Master effectively, users should be able to set the `PreferredLocations` list and define region priorities, so we expose that setting too.
`PreferredLocations` is not only beneficial for Multi Master accounts, but Non-Multi-Master accounts can benefit from it as explained in #363 
For this PR we are enabling  `UseMultipleWriteLocations` and  `PreferredLocations` for the Input/Output bindings and  `PreferredLocations` for the Trigger (the trigger reads the Change Feed, enabling Multi Master there has no real effect).
New tests were added to cover the new attributes.
The `Microsoft.Azure.DocumentDB.Core` package is …
=> [Cosmos DB] Implementing Multi Master and PreferredLocations

src/Packages/Packages.csproj, src/WebJobs.Extensions.ApiHub.NuGet/WebJobs.Extensions.ApiHub.nuspec, src/WebJobs.Extensions.DocumentDB.Nuget/WebJobs.Extensions.DocumentDB.nuspec, src/WebJobs.Extensions.Http.Nuget/WebJobs.Extensions.Http.nuspec, src/WebJobs.Extensions.MobileApps.Nuget/WebJobs.Extensions.MobileApps.nuspec, src/WebJobs.Extensions.NotificationHubs.Nuget/WebJobs.Extensions.NotificationHubs.nuspec, src/WebJobs.Extensions.NuGet/WebJobs.Extensions.nuspec, src/WebJobs.Extensions.SendGrid.Nuget/WebJobs.Extensions.SendGrid.nuspec, src/WebJobs.Extensions.Twilio.Nuget/WebJobs.Extensions.Twilio.nuspec, tools/NuGetProj.settings.targets
Fixes required to conform to new rules [here](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki?wikiVersion=GBwikiMaster&pagePath=%2FProduct%20Development%20Reference%2FNuGet%2FPublishing%20a%20NuGet%20package&anchor=troubleshooting-package-publishing-errors). We've already made these changes for v3.
=> Fixing Package metadata

src/WebJobs.Extensions.Http/HttpTriggerAttributeBindingProvider.cs, test/WebJobs.Extensions.Http.Tests/ClaimsPrincipalEndToEndTests.cs, test/WebJobs.Extensions.Http.Tests/HttpTriggerBindingTests.cs
This part of the identities bindings would have been a breaking change. We will have to reevaluate our approach for other languages, likely by adding this directly to the HttpContext object of the GRPC protocol.
=> Remove cross language support for identities bindings

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerBinding.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerHealthMonitor.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerObserver.cs, src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBListenerTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
This PR adds support for Partitioned leases collections, plus introduces multiple improvements:
* Uses DI to reuse existing Cosmos DB clients for the Trigger, this reduces connections when the Trigger is connecting to the same account as other Bindings or other Triggers (for example, 3 Triggers listening to the same account previously created 6 clients, now, they will all reuse the same one, unless they are connecting to different accounts or have different Preferred Locations).
* Adds the Monitoring service, so internal operational errors in the Trigger can be exposed to the external logs.
* Removes references to deprecated methods in the Change Feed SDK and uses the new builder pattern.
This PR fixes #518
=> Adding support for Partitioned Lease collections and monitoring

src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj
While putting together a project, I noticed that in order to use SendGrid's dynamic templates, you have to add a reference to the SendGrid 9.10.0 package into your Functions project ([sample repo here](https://github.com/burkeholland/serverless-sendgrid-report/blob/master/extensions.csproj)). 
Updating the dependency here should add support for dynamic templates (transactional templates).
=> Update SendGrid package to 9.10.0

build/common.props, src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj, src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj, src/WebJobs.Extensions/WebJobs.Extensions.csproj
Taking the same approach that we took with https://github.com/Azure/azure-webjobs-sdk/pull/2019. Now all versions are in a single file.
=> consolidating extension versioning into common.props

src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj, src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj, src/WebJobs.Extensions/Extensions/Timers/Bindings/TimerTriggerBinding.cs, src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs, src/WebJobs.Extensions/Extensions/Timers/Scheduling/DailySchedule.cs, src/WebJobs.Extensions/Extensions/Timers/Scheduling/WeeklySchedule.cs, src/WebJobs.Extensions/Extensions/Timers/TimerInfo.cs, src/WebJobs.Extensions/WebJobs.Extensions.csproj, test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/TimerInfoTests.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/TimerTriggerEndToEndTests.cs
Fixes #550
```
namespace WebJobsSandbox.One.Two.Three
{
public static class TimerSamples
{    
[FunctionName("MyTimer")]
public static void CronJob([TimerTrigger("*/15 * * * * *")] TimerInfo timerInfo)
{
}
}
}
```
Before: `The next 5 occurrences of the 'WebJobsSandbox.One.Two.Three.TimerSamples.CronJob' schedule`...
After: `The next 5 occurrences of the 'MyTimer' schedule`...
```
namespace WebJobsSandbox.One.Two.Three
{
public static class TimerSamples
{
public static void CronJob([TimerTrigger("*/15 * * * * *")] TimerInfo timerInfo)
{
}
}
}
```
Before: `The next 5 occurrences of the 'WebJobsSandbox.One.Two.Three.TimerSamples.CronJob' schedule`...
After: `The next 5 occurrences of the 'TimerSamples.CronJob' schedule`...
The schedule has been changed to be more easily parse-able and …
=> [TimerTrigger] improving logs

build/common.props, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
This PR adds support for the Cosmos DB Trigger to use Multi Master for the leases container. Previously, while the users could use PreferredLocations to specify reads from a particular region, writes for the leases state was being sent to the main hub region.
For users with Multi Master accounts, they can leverage local writes on any region, so this new attribute exposed in the Trigger can help them take advantage of that.
Additionally, bumping the version of Cosmos DB SDK and Change Feed SDK to get the latest fixes/improvements.
=> Enabling Multi Master for leases in Cosmos DB Trigger

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerHealthMonitor.cs
`LogError` was being called with the wrong parameters and not exposing the exception details.
=> Cosmos DB monitoring parameter order

build/common.props, src/WebJobs.Extensions.Http/Extensions/HttpRequestExtensions.cs
`EnableRewind()` went internal in ASP.NET Core 3.0 preview 7. But there's a direct replacement available in 2.x as well -- https://github.com/aspnet/AspNetCore/issues/12508#issuecomment-515601441.
Getting this in unblocks a bunch of .NET Core 3.0 tests in Functions.
=> [Http] replacing EnableRewind() with EnableBuffering()

src/WebJobs.Extensions.CosmosDB/Bindings/CosmosDBClientBuilder.cs, src/WebJobs.Extensions.CosmosDB/Config/CosmosDBExtensionConfigProvider.cs, src/WebJobs.Extensions.CosmosDB/Config/DefaultCosmosDBServiceFactory.cs, src/WebJobs.Extensions.CosmosDB/Config/ICosmosDBServiceFactory.cs, src/WebJobs.Extensions.CosmosDB/CosmosDBAttribute.cs, src/WebJobs.Extensions.CosmosDB/Services/CosmosDBService.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttribute.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBEnumerableBuilderTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBMockEndToEndTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/TestCosmosDBServiceFactory.cs
[See bug 574](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/574)
DateTimeOffset are having their Offset changed from the value stored to server local time
=> Add Default JsonSerializerSettings to DocumentClient to fix DateTimeOffset parsing

src/WebJobs.Extensions/Extensions/ExtensionsWebJobsStartup.cs, src/WebJobs.Extensions/Extensions/Warmup/Trigger/WarmupContext.cs, src/WebJobs.Extensions/Extensions/Warmup/Trigger/WarmupTriggerAttribute.cs, src/WebJobs.Extensions/Extensions/Warmup/Trigger/WarmupTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions/Extensions/Warmup/Trigger/WarmupTriggerBinding.cs, src/WebJobs.Extensions/Extensions/Warmup/WarmupConfigProvider.cs, src/WebJobs.Extensions/Extensions/Warmup/WarmupWebJobsBuilderExtensions.cs, test/WebJobs.Extensions.Http.Tests/ClaimsPrincipalEndToEndTests.cs, test/WebJobs.Extensions.Http.Tests/HttpTriggerEndToEndTests.cs, test/WebJobs.Extensions.Tests.Common/Helpers/Fakes/FakeActivator.cs, test/WebJobs.Extensions.Tests.Common/Helpers/Fakes/FakeTypeLocator.cs, test/WebJobs.Extensions.Tests.Common/Helpers/JobHostTestHelpers.cs, test/WebJobs.Extensions.Tests.Common/Helpers/TestExceptionHandlerFactory.cs, test/WebJobs.Extensions.Tests.Common/Helpers/TestJobHost.cs, test/WebJobs.Extensions.Tests/Extensions/Warmup/WarmupTriggerEndToEndTests.cs, test/WebJobs.Extensions.Tests/PublicSurfaceTests.cs
Related issue -- https://github.com/Azure/azure-functions-host/issues/4588
See related Host PR -- https://github.com/Azure/azure-functions-host/pull/4983
Adding a new Warmup extension that can be invoked through an admin API in the host. For more details, please look at the Host PR.
=> Add Warmup (trigger) extension

src/WebJobs.Extensions/Extensions/Timers/Bindings/TimerTriggerBinding.cs, src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.Logger.cs, src/WebJobs.Extensions/Extensions/Timers/Listener/TimerListener.cs, src/WebJobs.Extensions/Extensions/Timers/TimerInfo.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/Listener/TimerListenerTests.cs, test/WebJobs.Extensions.Tests/Extensions/Timers/TimerInfoTests.cs
Another piece to https://github.com/Azure/azure-functions-host/issues/4113. This will light up with https://github.com/Azure/azure-functions-host/pull/5114.
Not all of this was strictly necessary, but wanted to clean it up while I was in here. Now all of these will emit an event name for easier querying. And using the "functionName" key will allow us to extract that value in kusto (and shoebox) for the FunctionName column.
=> moving timer logs to use structured logging and EventIds

src/WebJobs.Extensions/Extensions/Timers/Config/TimerWebJobsBuilderExtensions.cs, src/WebJobs.Extensions/Extensions/Timers/Config/TimersOptions.cs
Resolves https://github.com/Azure/azure-webjobs-sdk-extensions/issues/625
=> Add documentation to make it clear that TimersOptions is currently unnecessary

build/common.props, src/ExtensionsSample/ExtensionsSample.csproj, src/ExtensionsSample/Samples/FileSamples.cs, src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, src/WebJobs.Extensions.Http/WebJobs.Extensions.Http.csproj, src/WebJobs.Extensions.MobileApps/WebJobs.Extensions.MobileApps.csproj, src/WebJobs.Extensions.SendGrid/WebJobs.Extensions.SendGrid.csproj, src/WebJobs.Extensions.Twilio/WebJobs.Extensions.Twilio.csproj, src/WebJobs.Extensions/Extensions/Timers/Scheduling/StorageScheduleMonitor.cs, src/WebJobs.Extensions/WebJobs.Extensions.csproj, test/WebJobs.Extensions.CosmosDB.Tests/WebJobs.Extensions.CosmosDB.Tests.csproj, test/WebJobs.Extensions.Http.Tests/HttpTriggerEndToEndTests.cs, test/WebJobs.Extensions.Http.Tests/WebJobs.Extensions.Http.Tests.csproj, test/WebJobs.Extensions.MobileApps.Tests/WebJobs.Extensions.MobileApps.Tests.csproj, test/WebJobs.Extensions.Tests/Extensions/Timers/Scheduling/StorageScheduleMonitorTests.cs
- Pull through Host.Storage 4.x and Extensions.Storage 4.x
- Bumped WebJobs.Extensions to 4.x
Replacement for #602
=> Update to storage SDK 11.x

build/common.props, src/ExtensionsSample/ExtensionsSample.csproj, src/WebJobs.Extensions.CosmosDB/WebJobs.Extensions.CosmosDB.csproj, test/WebJobs.Extensions.CosmosDB.Tests/WebJobs.Extensions.CosmosDB.Tests.csproj
The current versions, Microsoft.Azure.DocumentDB.Core,2.3.0 & Microsoft.Azure.DocumentDB.ChangeFeedProcessor,2.2.6 do not support OFFSET LIMIT clauses on cross-partition queries, but the new versions do. This PR simply updates those packages.
=> Update CosmosDB dependencies to latest versions for cross-partition offset/limit support

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs
As reported in issue #600, the UseDefaultJsonSerialization setting is not correctly passed by CosmosDbTriggerAttributeBindingProvider - it incorrectly passes the setting UseMultipleWriteLocations instead, which is irrelevant on the monitoring collection as this is only read from.
This means that using custom json serialization settings is not currently possible.
Fix is very small, unit test included which checks that the JsonConverter.DefaultSettings is actually accessed. This is a bit sneaky, but does accurately check the desired outcome and avoids having to change the code to be able to inspect the passed setting.
=> Fix for CosmosDbTrigger to honor UseDefaultJsonSerialization setting

build/common.props, src/WebJobs.Extensions.Http/HttpBindingApplicationBuilderExtension.cs, src/WebJobs.Extensions.Http/Routing/IWebJobsRouter.cs, src/WebJobs.Extensions.Http/Routing/WebJobsRouter.cs, test/WebJobs.Extensions.Http.Tests/WebJobsRouterTests.cs
This is the WebJobs.Extensions.Http part.
This combined with the PR for WebJobs.Script will move the
/admin/warmup call completely within the functions execution pipeline rather than being a separate controller
and will avoid all the JIT cost that incur during the first real function execution even when warmup triggers are present.
=> Improve functions startup time when warmup triggers are provided.

src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBListenerTests.cs
User agent was not correctly flowing inside the CFP and being used.
=> Cosmos DB: Fixing user agent

src/WebJobs.Extensions.CosmosDB/Config/CosmosDBExtensionConfigProvider.cs, src/WebJobs.Extensions.CosmosDB/CosmosDBUtility.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerAttributeBindingProvider.cs, src/WebJobs.Extensions.CosmosDB/Trigger/CosmosDBTriggerListener.cs, test/WebJobs.Extensions.CosmosDB.Tests/CosmosDBUtilityTests.cs, test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBListenerTests.cs
Current user agent wiring is not working correctly after SDK 2.12.0
=> Cosmos DB: Rewiring user agent initialization for 2.12.0
